"""create canonical domain and durable runtime

Revision ID: 4fdd8550e820
Revises:
Create Date: 2026-08-02 02:27:52.938786

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fdd8550e820"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_receipts",
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result_ref", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_command_receipts")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("event_sequence", sa.Integer(), nullable=False),
        sa.Column("active_requirement_revision_id", sa.UUID(), nullable=True),
        sa.Column("active_solution_version_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_sequence >= 0", name=op.f("ck_projects_event_sequence_nonnegative")
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_projects_revision_positive")),
        sa.ForeignKeyConstraint(
            ["id", "active_requirement_revision_id"],
            ["requirement_revisions.project_id", "requirement_revisions.id"],
            name="fk_project_active_requirement",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["id", "active_solution_version_id"],
            ["solution_versions.project_id", "solution_versions.id"],
            name="fk_project_active_solution",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "compatibility_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_compatibility_findings_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compatibility_findings")),
    )
    op.create_index(
        "ix_compatibility_project", "compatibility_findings", ["project_id"], unique=False
    )
    op.create_table(
        "decision_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_decision_requests_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_requests")),
        sa.UniqueConstraint("project_id", "id", name="uq_decision_project_id"),
    )
    op.create_index("ix_decisions_project", "decision_requests", ["project_id"], unique=False)
    op.create_table(
        "domain_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("project_seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("project_seq >= 1", name=op.f("ck_domain_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_domain_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_events")),
        sa.UniqueConstraint("project_id", "project_seq", name="uq_event_project_sequence"),
    )
    op.create_index(
        "ix_events_project_cursor", "domain_events", ["project_id", "project_seq"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parent_job_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.String(length=200), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("basis_project_revision", sa.Integer(), nullable=False),
        sa.Column("current_generation", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "basis_project_revision >= 1", name=op.f("ck_jobs_basis_revision_positive")
        ),
        sa.CheckConstraint("current_generation >= 0", name=op.f("ck_jobs_generation_nonnegative")),
        sa.CheckConstraint("profile_revision >= 1", name=op.f("ck_jobs_profile_revision_positive")),
        sa.ForeignKeyConstraint(
            ["parent_job_id"], ["jobs.id"], name=op.f("fk_jobs_parent_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_jobs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_project_status", "jobs", ["project_id", "status"], unique=False)
    op.create_table(
        "requirement_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirement_revisions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_requirement_project_id"),
        sa.UniqueConstraint("project_id", "revision", name="uq_requirement_project_revision"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_ref", sa.String(length=500), nullable=True),
        sa.Column("normalized_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("claim_generation >= 1", name=op.f("ck_attempts_generation_positive")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_attempts_number_positive")),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_attempts_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint("job_id", "claim_generation", name="uq_attempt_job_generation"),
        sa.UniqueConstraint("job_id", "number", name="uq_attempt_job_number"),
    )
    op.create_index("ix_attempts_lease", "attempts", ["status", "lease_expires_at"], unique=False)
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("requirement_revision_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "requirement_revision_id"],
            ["requirement_revisions.project_id", "requirement_revisions.id"],
            name="fk_module_project_requirement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_modules_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("project_id", "id", name="uq_module_project_id"),
        sa.UniqueConstraint("requirement_revision_id", "key", name="uq_module_requirement_key"),
    )
    op.create_index("ix_modules_project", "modules", ["project_id"], unique=False)
    op.create_table(
        "solution_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("requirement_revision_id", sa.UUID(), nullable=False),
        sa.Column("approved_decision_id", sa.UUID(), nullable=False),
        sa.Column("previous_version_id", sa.UUID(), nullable=True),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "approved_decision_id"],
            ["decision_requests.project_id", "decision_requests.id"],
            name="fk_solution_project_decision",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "previous_version_id"],
            ["solution_versions.project_id", "solution_versions.id"],
            name="fk_solution_project_previous",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "requirement_revision_id"],
            ["requirement_revisions.project_id", "requirement_revisions.id"],
            name="fk_solution_project_requirement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_solution_versions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_solution_versions")),
        sa.UniqueConstraint("project_id", "id", name="uq_solution_project_id"),
        sa.UniqueConstraint("project_id", "version", name="uq_solution_project_version"),
    )
    op.create_table(
        "attempt_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("result_hash", sa.String(length=64), nullable=False),
        sa.Column("disposition", sa.String(length=40), nullable=False),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition IN ('eligible', 'quarantined')",
            name=op.f("ck_attempt_results_disposition"),
        ),
        sa.CheckConstraint(
            "claim_generation >= 1", name=op.f("ck_attempt_results_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_results_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_attempt_results_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_attempt_results_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_results")),
        sa.UniqueConstraint("attempt_id", "result_hash", name="uq_attempt_result_hash"),
    )
    op.create_index(
        "ix_attempt_results_disposition", "attempt_results", ["disposition"], unique=False
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "module_id"],
            ["modules.project_id", "modules.id"],
            name="fk_candidate_project_module",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_candidates_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
    )
    op.create_index(
        "ix_candidates_project_module", "candidates", ["project_id", "module_id"], unique=False
    )
    op.create_table(
        "evidence_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "module_id"],
            ["modules.project_id", "modules.id"],
            name="fk_evidence_project_module",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evidence_bindings_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_bindings")),
    )
    op.create_index(
        "ix_evidence_project_module", "evidence_bindings", ["project_id", "module_id"], unique=False
    )
    op.create_table(
        "join_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_job_id", sa.UUID(), nullable=False),
        sa.Column("parent_attempt_id", sa.UUID(), nullable=False),
        sa.Column("parent_claim_generation", sa.Integer(), nullable=False),
        sa.Column("graph_step_id", sa.String(length=200), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("basis_project_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("expected_count", sa.Integer(), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis_project_revision >= 1", name=op.f("ck_join_groups_basis_revision_positive")
        ),
        sa.CheckConstraint(
            "expected_count BETWEEN 1 AND 2", name=op.f("ck_join_groups_expected_count_v0")
        ),
        sa.CheckConstraint(
            "parent_claim_generation >= 1", name=op.f("ck_join_groups_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["parent_attempt_id"],
            ["attempts.id"],
            name=op.f("fk_join_groups_parent_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["jobs.id"],
            name=op.f("fk_join_groups_parent_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_join_groups")),
        sa.UniqueConstraint("parent_attempt_id", "graph_step_id", name="uq_join_parent_step"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("solution_version_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "solution_version_id"],
            ["solution_versions.project_id", "solution_versions.id"],
            name="fk_observation_project_solution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_observations_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint("project_id", "id", name="uq_observation_project_id"),
    )
    op.create_index("ix_observations_project", "observations", ["project_id"], unique=False)
    op.create_table(
        "delegations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_job_id", sa.UUID(), nullable=False),
        sa.Column("parent_attempt_id", sa.UUID(), nullable=False),
        sa.Column("parent_claim_generation", sa.Integer(), nullable=False),
        sa.Column("join_group_id", sa.UUID(), nullable=False),
        sa.Column("child_job_id", sa.UUID(), nullable=False),
        sa.Column("graph_step_id", sa.String(length=200), nullable=False),
        sa.Column("profile_id", sa.String(length=200), nullable=False),
        sa.Column("profile_revision", sa.Integer(), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("shard_key", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("result_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "parent_claim_generation >= 1", name=op.f("ck_delegations_generation_positive")
        ),
        sa.CheckConstraint(
            "profile_revision >= 1", name=op.f("ck_delegations_profile_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["child_job_id"],
            ["jobs.id"],
            name=op.f("fk_delegations_child_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["join_group_id"],
            ["join_groups.id"],
            name=op.f("fk_delegations_join_group_id_join_groups"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_attempt_id"],
            ["attempts.id"],
            name=op.f("fk_delegations_parent_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["jobs.id"],
            name=op.f("fk_delegations_parent_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delegations")),
        sa.UniqueConstraint("child_job_id", name="uq_delegation_child_job"),
        sa.UniqueConstraint("idempotency_key", name="uq_delegation_idempotency_key"),
        sa.UniqueConstraint(
            "parent_attempt_id", "graph_step_id", "shard_key", name="uq_delegation_shard"
        ),
    )
    op.create_index(
        "ix_delegations_parent", "delegations", ["parent_job_id", "parent_attempt_id"], unique=False
    )
    op.create_table(
        "impact_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("base_solution_version_id", sa.UUID(), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "base_solution_version_id"],
            ["solution_versions.project_id", "solution_versions.id"],
            name="fk_impact_project_solution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "observation_id"],
            ["observations.project_id", "observations.id"],
            name="fk_impact_project_observation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_impact_analyses_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impact_analyses")),
        sa.UniqueConstraint("project_id", "id", name="uq_impact_project_id"),
    )
    op.create_index("ix_impacts_project", "impact_analyses", ["project_id"], unique=False)
    op.create_table(
        "join_receipts",
        sa.Column("join_group_id", sa.UUID(), nullable=False),
        sa.Column("parent_claim_generation", sa.Integer(), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["join_group_id"],
            ["join_groups.id"],
            name=op.f("fk_join_receipts_join_group_id_join_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("join_group_id", name=op.f("pk_join_receipts")),
    )
    op.create_table(
        "patch_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("impact_analysis_id", sa.UUID(), nullable=False),
        sa.Column("base_solution_version_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "base_solution_version_id"],
            ["solution_versions.project_id", "solution_versions.id"],
            name="fk_patch_project_solution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "impact_analysis_id"],
            ["impact_analyses.project_id", "impact_analyses.id"],
            name="fk_patch_project_impact",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_patch_sets_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patch_sets")),
        sa.UniqueConstraint("impact_analysis_id", name=op.f("uq_patch_sets_impact_analysis_id")),
    )
    op.create_foreign_key(
        "fk_project_active_requirement",
        "projects",
        "requirement_revisions",
        ["id", "active_requirement_revision_id"],
        ["project_id", "id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        "fk_project_active_solution",
        "projects",
        "solution_versions",
        ["id", "active_solution_version_id"],
        ["project_id", "id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.execute(
        """
        CREATE FUNCTION reject_solution_version_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'SolutionVersion is immutable';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER solution_versions_are_immutable
        BEFORE UPDATE OR DELETE ON solution_versions
        FOR EACH ROW EXECUTE FUNCTION reject_solution_version_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER solution_versions_are_immutable ON solution_versions")
    op.execute("DROP FUNCTION reject_solution_version_mutation()")
    op.drop_constraint("fk_project_active_solution", "projects", type_="foreignkey")
    op.drop_constraint("fk_project_active_requirement", "projects", type_="foreignkey")
    op.drop_table("patch_sets")
    op.drop_table("join_receipts")
    op.drop_index("ix_impacts_project", table_name="impact_analyses")
    op.drop_table("impact_analyses")
    op.drop_index("ix_delegations_parent", table_name="delegations")
    op.drop_table("delegations")
    op.drop_index("ix_observations_project", table_name="observations")
    op.drop_table("observations")
    op.drop_table("join_groups")
    op.drop_index("ix_evidence_project_module", table_name="evidence_bindings")
    op.drop_table("evidence_bindings")
    op.drop_index("ix_candidates_project_module", table_name="candidates")
    op.drop_table("candidates")
    op.drop_index("ix_attempt_results_disposition", table_name="attempt_results")
    op.drop_table("attempt_results")
    op.drop_table("solution_versions")
    op.drop_index("ix_modules_project", table_name="modules")
    op.drop_table("modules")
    op.drop_index("ix_attempts_lease", table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("requirement_revisions")
    op.drop_index("ix_jobs_project_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_events_project_cursor", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_index("ix_decisions_project", table_name="decision_requests")
    op.drop_table("decision_requests")
    op.drop_index("ix_compatibility_project", table_name="compatibility_findings")
    op.drop_table("compatibility_findings")
    op.drop_table("projects")
    op.drop_table("command_receipts")
    # ### end Alembic commands ###
