"""add_project_scoped_conversation

Revision ID: 6145ee9c54ae
Revises: i9c0d1e2f3a4
Create Date: 2026-08-11 15:08:47.532580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6145ee9c54ae'
down_revision: Union[str, Sequence[str], None] = 'i9c0d1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed')", name=op.f('ck_conversation_sessions_status')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_conversation_sessions_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index('uq_conversation_session_active_per_project', 'conversation_sessions', ['project_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_profile', sa.String(length=200), nullable=False),
    sa.Column('turn_type', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_conversation_turns_role')),
    sa.CheckConstraint("turn_type IN ('message', 'clarification', 'proposal')", name=op.f('ck_conversation_turns_turn_type')),
    sa.CheckConstraint('sequence >= 1', name=op.f('ck_conversation_turns_sequence_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_conversation_turns_session_id_conversation_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_conversation_turn_session_sequence')
    )
    op.create_index('uq_conversation_turn_idempotency_key', 'conversation_turns', ['session_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('conversation_action_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('proposed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_turn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('rewrite_requirements', 'add_module', 'start_research', 'change_selection', 'reshape_project')", name=op.f('ck_conversation_action_proposals_kind')),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'rejected', 'expired')", name=op.f('ck_conversation_action_proposals_status')),
    sa.ForeignKeyConstraint(['resolution_turn_id'], ['conversation_turns.id'], name=op.f('fk_conversation_action_proposals_resolution_turn_id_conversation_turns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], name=op.f('fk_conversation_action_proposals_turn_id_conversation_turns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_action_proposals'))
    )
    op.create_table('conversation_clarifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('resolved_by_turn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('requirement', 'constraint', 'module', 'selection', 'budget', 'other')", name=op.f('ck_conversation_clarifications_kind')),
    sa.CheckConstraint("status IN ('pending', 'resolved', 'expired')", name=op.f('ck_conversation_clarifications_status')),
    sa.ForeignKeyConstraint(['resolved_by_turn_id'], ['conversation_turns.id'], name=op.f('fk_conversation_clarifications_resolved_by_turn_id_conversation_turns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], name=op.f('fk_conversation_clarifications_turn_id_conversation_turns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_clarifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_clarifications')
    op.drop_table('conversation_action_proposals')
    op.drop_index('uq_conversation_turn_idempotency_key', table_name='conversation_turns', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('conversation_turns')
    op.drop_index('uq_conversation_session_active_per_project', table_name='conversation_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
