"""Canonical Aidison domain contracts."""

from aidison.domain.models import (
    Candidate,
    CompatibilityFinding,
    CompatibilityStatus,
    DecisionOption,
    DecisionRequest,
    DecisionStatus,
    EvidenceBinding,
    ImpactAnalysis,
    ImpactStatus,
    Module,
    ModulePatch,
    ModuleStage,
    Observation,
    PatchSet,
    Project,
    ProjectStage,
    RequirementRevision,
    RequirementStatus,
    SolutionVersion,
)

__all__ = [
    "CompatibilityFinding",
    "CompatibilityStatus",
    "Candidate",
    "DecisionOption",
    "DecisionRequest",
    "DecisionStatus",
    "EvidenceBinding",
    "ImpactAnalysis",
    "ImpactStatus",
    "Module",
    "ModulePatch",
    "ModuleStage",
    "Observation",
    "PatchSet",
    "Project",
    "ProjectStage",
    "RequirementRevision",
    "RequirementStatus",
    "SolutionVersion",
]
