"""add content addressed artifacts

Revision ID: 2e80b73c2d5a
Revises: 4fdd8550e820
Create Date: 2026-08-02 03:00:49.347707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e80b73c2d5a"
down_revision: str | Sequence[str] | None = "4fdd8550e820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("basis_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("storage_key", sa.String(length=96), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('present', 'missing', 'corrupt', 'quarantined', 'expired')",
            name=op.f("ck_artifacts_status"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_artifacts_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_artifacts_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint(
            "project_id", "attempt_id", "kind", "content_hash", name="uq_artifact_attempt_kind_hash"
        ),
    )
    op.create_index(
        "ix_artifacts_project_status", "artifacts", ["project_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_artifacts_project_status", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
