"""add idempotent runtime job requests

Revision ID: 53e910e5f198
Revises: 2e80b73c2d5a
Create Date: 2026-08-02 03:17:46.243906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53e910e5f198"
down_revision: str | Sequence[str] | None = "2e80b73c2d5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("request_key", sa.String(length=300), nullable=True))
    op.create_unique_constraint(op.f("uq_jobs_request_key"), "jobs", ["request_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_jobs_request_key"), "jobs", type_="unique")
    op.drop_column("jobs", "request_key")
    # ### end Alembic commands ###
